name: 버그 리포트
description: 발생한 문제에 대해 알려주세요
title: "[Bug]: "
labels: [bug]
body:
  - type: input
    id: summary
    attributes:
      label: 요약
      description: 어떤 문제가 발생했나요?
      placeholder: 예) 알림이 뜨지 않아요
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 재현 방법
      description: 문제가 발생하는 과정을 단계별로 알려주세요
      placeholder: 예)  
        1. 확장 프로그램을 설치하고  
        2. 3시에 알림을 기다렸는데  
        3. 아무런 알림이 안 떴어요
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 사용자 환경
      description: 사용중인 운영체제나 알림 설정 상태를 알려주세요
      placeholder: 예) 윈도우 11 / 크롬 알림 허용

  - type: textarea
    id: additional
    attributes:
      label: 추가 정보
      description: 스크린샷이나 다른 참고 사항이 있다면 여기에 적어주세요
